#pragma once
#define GPIO_SetPin(x) GPIO_SetBits(x.GPIOx,x.pinNum)
#define GPIO_ResetPin(x) GPIO_ResetBits(x.GPIOx,x.pinNum)
#define GPIO_Read(x) (x.GPIOx->IDR & x.pinNum)
#include "string.h"
#include "stdlib.h"
#include "stm32f4xx.h"
#include "time_service.h"
#include "global_macros.h"
#include "stm32f4xx_global_macros.h"
#include "uart_handle_mock.h"
#include "uart_handle.h"
#include "stm32f4xx.h"
#include "stm32f4xx_tim.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_i2c.h"
#include "stm32f4xx_usart.h"
#include "stm32f4xx_adc.h"
#include "stm32f4xx_dma.h"
#include "stm32f4xx_dma2d.h"
#include "stm32f4xx_exti.h"
//#include "global_macros.h"
#include "uart_handle_mock.h"
#include "uart_handle.h"
#include "stm32f4xx.h"
#include "misc.h"
